// import dubaiListings from "../data/dubaiListings";
const dubaiListings = [
  {
    id: 1,
    name: "Green Villa",
    type: "sale",
    offer: true,
    regularPrice: 1200000,
    discountPrice: 1100000,
    location: "Dubai Marina, Dubai",
    beds: 4,
    baths: 3,
    imageUrls: ["/2.jpg", "/1.jpg"],
    description: "Luxury villa with 4 bedrooms, private pool and garden",
    userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 2,
    name: "Beach Apartment",
    type: "rent",
    offer: false,
    regularPrice: 3500,
    location: "Jumeirah Beach, Dubai",
    beds: 2,
    baths: 2,
    imageUrls: ["/4.jpg", "/3.jpg"],
    description: "Cozy 2-bedroom apartment near the beach with sea view",
     userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 3,
    name: "Downtown Apartment",
    type: "sale",
    offer: true,
    regularPrice: 850000,
    discountPrice: 800000,
    location: "Downtown Dubai",
    beds: 3,
    baths: 2,
    imageUrls: ["/5.jpg", "/8.jpg"],
    description: "Modern apartment in the heart of Dubai, 3 bedrooms",
     userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 4,
    name: "Suburban House",
    type: "rent",
    offer: false,
    regularPrice: 2500,
    location: "Al Barsha, Dubai",
    beds: 3,
    baths: 2,
    imageUrls: ["/7.jpg", "/8.jpg"],
    description: "Family-friendly house with garden and 3 bedrooms",
     userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 5,
    name: "Luxury Penthouse",
    type: "sale",
    offer: true,
    regularPrice: 2200000,
    discountPrice: 2100000,
    location: "Palm Jumeirah, Dubai",
    beds: 4,
    baths: 4,
    imageUrls: ["/1.jpg", "/2.jpg"],
    description: "Spacious penthouse with terrace and sea view",
     userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 6,
    name: "Modern Studio",
    type: "rent",
    offer: false,
    regularPrice: 1800,
    location: "Business Bay, Dubai",
    beds: 1,
    baths: 1,
    imageUrls: ["/3.jpg", "/4.jpg"],
    description: "Compact modern studio in city center, ideal for singles",
     userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 7,
    name: "Family Villa",
    type: "sale",
    offer: true,
    regularPrice: 1350000,
    discountPrice: 1280000,
    location: "Emirates Hills, Dubai",
    beds: 5,
    baths: 4,
    imageUrls: ["/5.jpg", "/6.jpg"],
    description: "Beautiful 5-bedroom family villa with private garden",
     userRef: '64f2a5c1234567890abcdef',
  },
  {
    id: 8,
    name: "City Apartment",
    type: "rent",
    offer: true,
    regularPrice: 3000,
    discountPrice: 2800,
    location: "Downtown Dubai",
    beds: 2,
    baths: 2,
    imageUrls: ["/7.jpg", "/8.jpg"],
    description: "2-bedroom apartment in central Dubai with balcony view",
     userRef: '64f2a5c1234567890abcdef',
  },
];

export default dubaiListings;
